// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yohnnn/booking_service/internal/cache (interfaces: ConcertCacheRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_cache.go -package=mocks github.com/yohnnn/booking_service/internal/cache ConcertCacheRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/yohnnn/booking_service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockConcertCacheRepository is a mock of ConcertCacheRepository interface.
type MockConcertCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConcertCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockConcertCacheRepositoryMockRecorder is the mock recorder for MockConcertCacheRepository.
type MockConcertCacheRepositoryMockRecorder struct {
	mock *MockConcertCacheRepository
}

// NewMockConcertCacheRepository creates a new mock instance.
func NewMockConcertCacheRepository(ctrl *gomock.Controller) *MockConcertCacheRepository {
	mock := &MockConcertCacheRepository{ctrl: ctrl}
	mock.recorder = &MockConcertCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConcertCacheRepository) EXPECT() *MockConcertCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConcertCacheRepository) Delete(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConcertCacheRepositoryMockRecorder) Delete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConcertCacheRepository)(nil).Delete), ctx)
}

// Get mocks base method.
func (m *MockConcertCacheRepository) Get(ctx context.Context) ([]models.Concert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]models.Concert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConcertCacheRepositoryMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConcertCacheRepository)(nil).Get), ctx)
}

// Set mocks base method.
func (m *MockConcertCacheRepository) Set(ctx context.Context, concerts []models.Concert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, concerts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockConcertCacheRepositoryMockRecorder) Set(ctx, concerts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockConcertCacheRepository)(nil).Set), ctx, concerts)
}
