// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yohnnn/booking_service/internal/event (interfaces: EventProducer)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_event.go -package=mocks github.com/yohnnn/booking_service/internal/event EventProducer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	event "github.com/yohnnn/booking_service/internal/event"
	gomock "go.uber.org/mock/gomock"
)

// MockEventProducer is a mock of EventProducer interface.
type MockEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockEventProducerMockRecorder
	isgomock struct{}
}

// MockEventProducerMockRecorder is the mock recorder for MockEventProducer.
type MockEventProducerMockRecorder struct {
	mock *MockEventProducer
}

// NewMockEventProducer creates a new mock instance.
func NewMockEventProducer(ctrl *gomock.Controller) *MockEventProducer {
	mock := &MockEventProducer{ctrl: ctrl}
	mock.recorder = &MockEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProducer) EXPECT() *MockEventProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventProducer)(nil).Close))
}

// SendBookingCreated mocks base method.
func (m *MockEventProducer) SendBookingCreated(ctx context.Context, arg1 event.BookingCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBookingCreated", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBookingCreated indicates an expected call of SendBookingCreated.
func (mr *MockEventProducerMockRecorder) SendBookingCreated(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBookingCreated", reflect.TypeOf((*MockEventProducer)(nil).SendBookingCreated), ctx, arg1)
}
